// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHvTzDSTRrObYUf9bpBGZN0KYxHVYC-bE',
    appId: '1:643663917738:web:11324636b13278c1bad6d3',
    messagingSenderId: '643663917738',
    projectId: 'movie-20b81',
    authDomain: 'movie-20b81.firebaseapp.com',
    storageBucket: 'movie-20b81.firebasestorage.app',
    measurementId: 'G-MCYV40T9MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH0v1rG5ibt139HZMZ2H99sIDfqCXCkoE',
    appId: '1:643663917738:android:7745714c35209c0fbad6d3',
    messagingSenderId: '643663917738',
    projectId: 'movie-20b81',
    storageBucket: 'movie-20b81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA3KIoTfAwojQSLB8LN0nY51mQgZbVIIs',
    appId: '1:643663917738:ios:2e051023f31a0a4ebad6d3',
    messagingSenderId: '643663917738',
    projectId: 'movie-20b81',
    storageBucket: 'movie-20b81.firebasestorage.app',
    iosBundleId: 'com.example.movieTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA3KIoTfAwojQSLB8LN0nY51mQgZbVIIs',
    appId: '1:643663917738:ios:2e051023f31a0a4ebad6d3',
    messagingSenderId: '643663917738',
    projectId: 'movie-20b81',
    storageBucket: 'movie-20b81.firebasestorage.app',
    iosBundleId: 'com.example.movieTickets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHvTzDSTRrObYUf9bpBGZN0KYxHVYC-bE',
    appId: '1:643663917738:web:11324636b13278c1bad6d3',
    messagingSenderId: '643663917738',
    projectId: 'movie-20b81',
    authDomain: 'movie-20b81.firebaseapp.com',
    storageBucket: 'movie-20b81.firebasestorage.app',
    measurementId: 'G-MCYV40T9MP',
  );

}